HELP_TEXT = (
    "📖 Available Commands\n"
    "━━━━━━━━━━━━━━\n\n"
    "🏠 /start\n"
    "   Show the main menu with buttons.\n\n"
    "🔑 /signin\n"
    "   Link your real jsweboosting.site account to view your\n"
    "   actual balance, orders, and total spend.\n\n"
    "🧮 /calc\n"
    "   Estimate the price of a service before ordering\n"
    "   (type Local ID, then quantity).\n\n"
    "🏆 /leaderboard\n"
    "   View the Top Spenders leaderboard (works in the group).\n\n"
    "📅 /schedule\n"
    "   Schedule an order reminder for a future time (supports\n"
    "   multiple/bulk items) — I'll DM you the details when it's time.\n\n"
    "💡 Tip: In the group chat, just type these words and the bot\n"
    "will auto-reply — no command needed:\n"
    "   • \"site\" — get the official site link\n"
    "   • \"add funds\" — get payment/GCash details\n"
    "   • \"reco\" — get the recommended services channel link\n\n"
    "🔔 You'll automatically get a DM notification when your\n"
    "order status changes — no need to keep checking manually.\n\n"
    "🛠 Admin Commands (admin/owner only)\n"
    "━━━━━━━━━━━━━━\n\n"
    "📌 /reco\n"
    "   Paste a recommendation list from the panel owner (z-smm.com) —\n"
    "   auto-translates panel IDs to dashboard IDs and posts the\n"
    "   result to the Reco channel.\n\n"
    "🎯 /dexreco\n"
    "   Auto-fetches the Recommended Services list directly from\n"
    "   DexBelleSMM (no typing needed), translates the IDs, and\n"
    "   posts to the Reco channel.\n\n"
    "📊 /syncdash\n"
    "   Show current dashboard data status (count, last synced).\n"
    "   Use `sync` in Termux to actually refresh the data.\n\n"
    "🔎 /finddash <panel_id>\n"
    "   Look up ALL dashboard matches for a given panel ID (shows\n"
    "   every provider that uses that ID number).\n\n"
    "🔍 /searchdash <keyword>\n"
    "   Search dashboard services by name.\n\n"
    "🗺 /map, /maplist, /findid\n"
    "   Manual panel↔local ID mapping tools (legacy, rarely needed\n"
    "   now that /finddash works automatically).\n\n"
    "💰 /addfunds <username> <amount>\n"
    "   Instantly credit a user's real site balance (owner-only,\n"
    "   restricted to specific Telegram IDs).\n\n"
    "📢 /broadcast <message>\n"
    "   Send a message to every registered user."
)


async def help_command(update, context):
    await update.message.reply_text(HELP_TEXT)